INSERT INTO roles (roleName,camp) VALUES ('villager','villagers');
INSERT INTO roles (roleName,camp) VALUES ('knight','villagers');
INSERT INTO roles (roleName,camp) VALUES ('necro','villagers');
INSERT INTO roles (roleName,camp) VALUES ('wolf','wolves');
INSERT INTO winner (userName, camp) VALUES ('user1', 'wolves');
INSERT INTO winner (userName, camp) VALUES ('user1', 'villagers');
INSERT INTO winner (userName, camp) VALUES ('user1', 'wolves');
INSERT INTO winner (userName, camp) VALUES ('user2', 'villagers');
INSERT INTO winner (userName, camp) VALUES ('user2', 'villagers');
INSERT INTO winner (userName, camp) VALUES ('user3', 'villagers');
INSERT INTO winner (userName, camp) VALUES ('user3', 'villagers');
INSERT INTO winner (userName, camp) VALUES ('user4', 'villagers');
INSERT INTO winner (userName, camp) VALUES ('user1', 'villagers');
